### ISSUE TITLE
6 not getting accepted

### ISSUE THREAD

**Issue by Climax777** [drewlustro/shader-school-answers#1]
6 doesn't get accepted

**Comment by vicapow** [comment]
``` glsl
mat2 matrixPower(highp mat2 m, int n) {
  // a matrix raised to the 0th power is the identity
  if (n == 0) {
    return mat2(1.0);
  }
  highp mat2 p = mat2(1.0) * m; // copy
  for(int i = 1; i < 16; i++) {
    if (i == n) return p;
    p *= m;
  }
  return p;
}

//Do not change this line or the name of the above function
#pragma glslify: export(matrixPower)
```

**Comment by shkfnly** [comment]
Hey can you explain why the fix is needed? Why wouldn't it just be possible to make the the second parameter of the for loop i < n

**Comment by drewlustro** [comment]
@shkfnly the fix proposed by @vicapow works, but is a little unclear. In the loop, `i` can only be compared to a 'constant expression', in this case `16`. To make things clearer, it is recommended to create a constant with proper label:

More info: http://stackoverflow.com/questions/6247572/variable-array-index-not-possible-in-webgl-shaders

I also tried naming the parameter `const in int n`, but glsl throws an error and complains that `n` is still considered a non-constant expression in the for-loop. Perhaps this is a `#version` declarative problem within shader-school.

As far as I can tell, 6 is reasonably proper.
